### PR TITLE
Fix bug with context switcher when visiting docs for first time

### LINKED ISSUE #424: Language specifier disappears
When I open a page for a specific language, e.g., a [querying page for javascript](https://docs.ditto.live/javascript/common/concepts/querying), I see the language specifier, which is set to Javascript. However, if I keep the page open in a tab for awhile (Chrome), then the language specifier. To get it back I need to refresh the page. See this screenshot where the specifier is missing and then I do refresh, so it reappears:

https://user-images.githubusercontent.com/1726044/212651131-32fb8c88-00f6-4657-9767-2832e9a8a348.mov

### PR DESCRIPTION
**Pull request by okdistribute**
fixes #424 and #427 

Bonus while I was here: add NodeJS to valid language for raspberrypi docs

### CODE REVIEW

File: src/components/SnippetGroup.tsx [hunk 1]
```diff
@@ -5,6 +5,19 @@ import snippets from '../../snippets.json';
 import CodeBlock from '@theme/CodeBlock';
 import Tabs from '../theme/Tabs';
 import TabItem from '../theme/TabItem';
+import LANGUAGES from './Languages.js';
```
Comment (okdistribute) [inline src/components/SnippetGroup.tsx:8]: This is repetition but for the sake of time I just repeated it. This should probably be it's own `useEffect`.
